services:
    lighthart_docdownloader.file_list_reader:
        class: Lighthart\DocumentDownloaderBundle\DocumentDownloader\FileListReader
        arguments: [ %kernel.root_dir% ]

    lighthart_docdownloader.downloader:
        class: Lighthart\DocumentDownloaderBundle\DocumentDownloader\Downloader
        arguments: [ "@lighthart_docdownloader.file_list_reader", "@security.token_storage" ]

    lighthart_docdownloader.twig.extension:
        class: Lighthart\DocumentDownloaderBundle\Twig\Extension\DocumentDownloaderExtension
        arguments: [ "@router" ]
        tags:
            - { name: twig.extension }